### ISSUE TITLE
 Error: {error,emfile}

### ISSUE THREAD

**Issue by adyshimony** [dscape/nano#360]
Hi,

I am querying 60 DBs one after the other, depend on the results from every DB, I am getting ad different DB errors, every time on different DB, sometime on one, sometime on few. 
I I query only 10 DBs for example, I get no errors.

The error is:

Error: {gen_server,call,
     {get_index,
         {couch_mrview_index,
             {mrst,
                 <<142,84,225,128,226,114,69,21,204,199,179,167,78,218,217,132>>,
                 nil,undefined,
                 <<"shards/e0000000-ffffffff/supernodedb-3700000-3799999.1520034961">>,
                 <<"_design/fromDoc">>,<<"javascript">>,[],false,false,
                 {[]},
                 [{mrview,0,0,0,
                      [<<"view">>],
                      [],
                      <<"function (doc) {\n                                if (doc.from) {\n                                    emit(doc.from, null);\n              }\n                            }">>,
                      nil,nil,nil,false,false,[]}],
                 nil,nil,0,0,undefined,undefined,undefined,undefined,
                 undefined,nil},
             <<"shards/e0000000-ffffffff/supernodedb-3700000-3799999.1520034961">>,
             <<142,84,225,128,226,114,69,21,204,199,179,167,78,218,217,132>>}},
     infinity]}
    at Object.createErr [as create] (/home/adys/Sources/ether-super-node/node_modules/errs/lib/errs.js:97:11)
    at Request._callback (/home/adys/Sources/ether-super-node/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/home/adys/Sources/ether-super-node/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/adys/Sources/ether-super-node/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/adys/Sources/ether-super-node/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

Sometimes I am getting the error:

error:  Error: {error,emfile}
    at Request._callback (/home/adys/Sources/ether-super-node/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/home/adys/Sources/ether-super-node/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/adys/Sources/ether-super-node/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/adys/Sources/ether-super-node/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

or

Error: {{badmatch,{error,emfile}},
  {gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},
  {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    at Object.createErr [as create] (/home/adys/Sources/ether-super-node/node_modules/errs/lib/errs.js:97:11)
    at Request._callback (/home/adys/Sources/ether-super-node/node_modules/nano/lib/nano.js:248:15)
    at Request.self.callback (/home/adys/Sources/ether-super-node/node_modules/request/request.js:186:22)
    at Request.emit (events.js:160:13)
    at Request.<anonymous> (/home/adys/Sources/ether-super-node/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:160:13)
    at IncomingMessage.<anonymous> (/home/adys/Sources/ether-super-node/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:255:19)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

Thanks,
Ady.

**Comment by adyshimony** [comment]
this is an example
https://gist.github.com/adyshimony/a45ee9488757ec48604faffdec215765
